"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Braces, ChevronLeft, ChevronRight, CircleHelp, Code2, Info, LockKeyhole, Pause, Play, Search, ShieldCheck, SkipBack, SkipForward, Workflow, X, Zap, ZoomIn, ZoomOut } from "lucide-react";

type Mode = "explore" | "flow" | "gates" | "failure" | "advanced";
type Level = "foundation" | "practitioner" | "internals";
type Traffic = "control" | "data" | "both";
type NodeId = "clients" | "controllers" | "api" | "etcd" | "scheduler" | "external" | "nodeA" | "nodeB" | "kubeletA" | "kubeletB" | "runtimeA" | "runtimeB" | "podsA" | "podsB" | "network" | "storage";
type Step = { title:string; detail:string; nodes:NodeId[]; op?:string; kind?:"request"|"watch"|"event"|"status"|"external"|"failure"|"data"; object?:string; desired?:number; observed?:number; yaml?:string };
type Flow = { id:number; title:string; short:string; level:Level; steps:Step[] };

const S=(title:string,detail:string,nodes:NodeId[],op?:string,kind:Step["kind"]="request",object?:string,yaml?:string):Step=>({title,detail,nodes,op,kind,object,yaml});
const flows:Flow[]=[
 {id:1,title:"Create a Deployment",short:"Intent → Pods → Reality",level:"foundation",steps:[
  {...S("Apply desired state","kubectl submits a Deployment with three desired replicas. No containers exist yet.",["clients","api"],"CREATE / PATCH","request","Deployment","apiVersion: apps/v1\nkind: Deployment\nspec:\n  replicas: 3"),desired:3,observed:0},
  {...S("Pass request gates","The API server authenticates, authorizes, admits and validates the write.",["api"],"AUTHN → AUTHZ → ADMISSION","request","Deployment"),desired:3,observed:0},
  {...S("Commit shared state","The accepted Deployment becomes durable API state backed by etcd.",["api","etcd"],"COMMIT","request","Deployment"),desired:3,observed:0},
  {...S("Controllers observe","Deployment and ReplicaSet controllers react through LIST/WATCH and create the next desired objects.",["controllers","api"],"WATCH + CREATE","watch","ReplicaSet + Pods"),desired:3,observed:0},
  {...S("Record placement","The scheduler sees unscheduled Pods, selects Nodes, and records bindings through the API.",["scheduler","api","nodeA","nodeB"],"BIND Pods","request","Pod bindings"),desired:3,observed:0},
  {...S("Kubelets execute","Each kubelet observes Pods assigned to its Node and asks its local runtime to create containers.",["api","kubeletA","kubeletB","runtimeA","runtimeB","podsA","podsB"],"WATCH assigned Pods","watch","PodSpecs"),desired:3,observed:2},
  {...S("Reality returns","Kubelets update Pod status through the API. Independent control loops converge.",["kubeletA","kubeletB","api","controllers"],"PATCH status","status","Pod/status","status:\n  replicas: 3\n  readyReplicas: 3"),desired:3,observed:3}]},
 {id:2,title:"Schedule a Pod",short:"Filter → score → bind",level:"foundation",steps:[S("Observe an unbound Pod","The scheduler watches for Pods whose spec.nodeName is unset.",["scheduler","api"],"WATCH Pods","watch","Pod"),S("Filter and score Nodes","Cached capacity, taints, affinity, topology and storage constraints drive placement.",["scheduler","nodeA","nodeB"],"FILTER + SCORE","event","Node candidates"),S("Persist the decision","The scheduler binds the Pod to worker-b through the API. It does not start a container.",["scheduler","api","nodeB"],"BIND worker-b","request","Pod/binding","spec:\n  nodeName: worker-b")]},
 {id:3,title:"Start a Pod on a Node",short:"PodSpec → node reality",level:"foundation",steps:[S("Observe assigned Pod","worker-b's kubelet watches the API for Pods assigned to worker-b.",["api","kubeletB"],"WATCH assigned Pods","watch","PodSpec"),S("Prepare dependencies","The kubelet resolves ConfigMaps, Secrets, volumes and networking.",["kubeletB","api","storage","network"],"GET dependencies","request","ConfigMap + Secret + PVC"),S("Execute locally","CRI, CNI and CSI workflows turn assigned state into node-local reality.",["kubeletB","runtimeB","podsB","network","storage"],"CRI / CNI / CSI","data","Container")]},
 {id:4,title:"Pod Status Reporting",short:"Reality → status → loop",level:"foundation",steps:[S("Inspect local reality","The kubelet reads container and probe results from the node.",["runtimeA","podsA","kubeletA"],"OBSERVE","event","Container state"),S("Report status","The kubelet patches the Pod status subresource through the API server.",["kubeletA","api"],"PATCH /status","status","Pod/status"),S("Controllers react","Status events reach interested controllers through WATCH; reconciliation continues.",["api","controllers"],"MODIFIED Pod","event","Pod")]},
 {id:5,title:"Node Joins Cluster",short:"Register capacity",level:"practitioner",steps:[S("Register Node","A new kubelet registers its Node object through the API server.",["kubeletB","api"],"CREATE Node","request","Node"),S("Publish capacity","Addresses, capacity, allocatable, conditions and labels become shared state.",["api","etcd","nodeB"],"UPDATE Node/status","status","Node"),S("Become schedulable","Controllers and the scheduler observe the new Node through the API.",["api","controllers","scheduler","nodeB"],"ADDED Node","event","Node")]},
 {id:6,title:"Node Heartbeat",short:"Status + lightweight Lease",level:"practitioner",steps:[S("Renew Lease","The kubelet periodically renews its Lease in kube-node-lease.",["kubeletA","api"],"UPDATE Lease","status","Lease"),S("Update Node status","Less frequent Node.status updates carry health and condition detail.",["kubeletA","api"],"PATCH Node/status","status","Node"),S("Observe liveness","Node lifecycle loops use both signals; a Lease is a lightweight heartbeat.",["controllers","api","nodeA"],"WATCH Lease + Node","watch","Lease")]},
 {id:7,title:"Node Failure",short:"Missing Lease → replacement",level:"practitioner",steps:[S("Node loses power","worker-b stops renewing its Lease; lifecycle thresholds still matter.",["nodeB","kubeletB","api"],"LEASE STOPS","failure","Lease"),S("Control plane detects","Node lifecycle logic transitions Node readiness over time.",["controllers","api","nodeB"],"Ready: Unknown","failure","Node/status"),S("Reconcile availability","Reduced availability eventually causes a replacement Pod on a healthy Node.",["controllers","api","scheduler","nodeA"],"CREATE replacement Pod","request","Pod")]},
 {id:8,title:"Service + EndpointSlice",short:"Selectors become backends",level:"practitioner",steps:[S("Observe Service and Pods","The EndpointSlice controller watches selector-based Services and matching Pods.",["controllers","api","podsA","podsB"],"WATCH Service + Pods","watch","Service"),S("Publish endpoints","It writes EndpointSlices containing eligible backend Pod addresses.",["controllers","api"],"UPDATE EndpointSlice","request","EndpointSlice"),S("Expose routing state","Service dataplanes consume EndpointSlices as API source of truth.",["api","network"],"WATCH EndpointSlices","watch","EndpointSlice")]},
 {id:9,title:"kube-proxy Programming",short:"API state → node rules",level:"practitioner",steps:[S("Watch routing objects","kube-proxy watches Services and EndpointSlices through the API.",["api","network"],"WATCH Services","watch","Service + EndpointSlice"),S("Program each Node","It synchronizes iptables, nftables or legacy IPVS forwarding state.",["network","nodeA","nodeB"],"SYNC RULES","data","Node rules"),S("Route application traffic","Service traffic follows the dataplane to Pods—not the API server. eBPF may replace kube-proxy.",["network","podsA","podsB"],"DATA PLANE","data","Packets")]},
 {id:10,title:"ConfigMap / Secret",short:"API data → container",level:"practitioner",steps:[S("Resolve references","The kubelet obtains referenced ConfigMaps and Secrets through the API.",["kubeletA","api"],"GET ConfigMap / Secret","request","ConfigMap + Secret"),S("Materialize values","The kubelet projects data into volumes or captures environment values at start.",["api","kubeletA","runtimeA"],"PROJECT","event","Projected data"),S("Understand updates","Projected volumes may refresh; environment variables do not change inside an existing process.",["kubeletA","podsA"],"REFRESH","event","Mounted data")]},
 {id:11,title:"ServiceAccount API Call",short:"A Pod becomes a client",level:"practitioner",steps:[S("Use workload identity","A Pod uses a projected ServiceAccount token to call the API Service.",["podsA","api"],"HTTPS + Bearer token","request","ServiceAccount token"),S("Pass identity gates","Authentication establishes identity; authorization decides allowed operations.",["podsA","api"],"AUTHN → AUTHZ","request","UserInfo"),S("Read or mutate state","Reads bypass normal admission; applicable writes continue through admission.",["api","etcd"],"GET or CREATE","request","API resource")]},
 {id:12,title:"Horizontal Pod Autoscaler",short:"Metrics → desired scale",level:"practitioner",steps:[S("Read metrics","The HPA controller reads resource or custom metrics through an API.",["external","api","controllers"],"GET metrics","request","MetricValue"),S("Compute desired replicas","Current CPU is high: current replicas 3, desired replicas 8.",["controllers"],"CALCULATE 3 → 8","event","Scale","spec:\n  replicas: 8"),S("Update scale","HPA updates /scale. It does not directly create Pods.",["controllers","api"],"PATCH /scale","request","Deployment/scale"),S("Normal loops take over","Controllers create Pods; scheduler and kubelets place and execute them.",["controllers","api","scheduler","kubeletA","kubeletB"],"RECONCILE","watch","Pods")]},
 {id:13,title:"PersistentVolume / CSI",short:"PVC → provider → mount",level:"practitioner",steps:[S("Declare a claim","A PVC is accepted as Kubernetes API state.",["clients","api","etcd"],"CREATE PVC","request","PersistentVolumeClaim"),S("Provision storage","The CSI provisioner watches PVCs and calls the storage provider.",["api","storage","external"],"WATCH + CREATE VOLUME","external","PVC"),S("Publish Kubernetes state","PV, binding and relevant VolumeAttachment state is written through the API.",["storage","api"],"CREATE PV / BIND","request","PV + VolumeAttachment"),S("Mount on the Node","Kubelet invokes CSI node operations to stage, publish and mount into the Pod.",["api","kubeletB","storage","podsB"],"STAGE / PUBLISH","external","Volume")]},
 {id:14,title:"Service type LoadBalancer",short:"Declaration → cloud LB",level:"practitioner",steps:[S("Declare external exposure","A LoadBalancer Service enters through the API.",["clients","api"],"CREATE Service","request","Service"),S("Provider controller reacts","A provider controller watches it and calls an external cloud API.",["controllers","api","external"],"WATCH + CLOUD API","external","Service"),S("Status returns","The controller writes the provisioned address to Service.status.",["external","controllers","api"],"PATCH Service/status","status","Service/status")]},
 {id:15,title:"Ingress / Gateway",short:"Routes → dataplane config",level:"practitioner",steps:[S("Declare routes","Ingress, Gateway or HTTPRoute objects enter through the API.",["clients","api"],"CREATE HTTPRoute","request","HTTPRoute"),S("Controller watches","The selected controller observes routes, Services and backends.",["controllers","api"],"WATCH Gateway API","watch","Gateway + HTTPRoute"),S("Configure dataplane","It reconciles Envoy, NGINX or a cloud load balancer and reports status.",["controllers","external","network","api"],"CONFIGURE + STATUS","external","Gateway/status")]},
 {id:16,title:"Operator / CRD",short:"Custom API, same pattern",level:"internals",steps:[S("Create custom resource","A DatabaseCluster custom resource is stored like other API resources.",["clients","api","etcd"],"CREATE DatabaseCluster","request","Custom Resource"),S("Operator observes","The Operator watches its custom resource through the API.",["external","api"],"WATCH DatabaseCluster","watch","DatabaseCluster"),S("Reconcile children","It creates StatefulSets, Services, Secrets, ConfigMaps and PVCs.",["external","api","controllers","storage"],"CREATE child resources","request","StatefulSet + PVC"),S("Publish conditions","The Operator updates status using the same pattern as built-in controllers.",["external","api"],"PATCH status","status","Custom Resource/status")]},
 {id:17,title:"Admission Webhook",short:"API server calls outward",level:"internals",steps:[S("Write reaches admission","After authentication and authorization, a write reaches mutating then validating admission.",["clients","api"],"WRITE","request","Pod"),S("Call webhook","The API server actively sends an AdmissionReview. This is not a WATCH.",["api","external"],"AdmissionReview","external","AdmissionReview"),S("Allow, deny or mutate","The webhook returns allow, deny or a patch; timeout follows failurePolicy.",["external","api"],"RESPONSE / PATCH","external","AdmissionResponse")]},
 {id:18,title:"kubectl logs",short:"Special API → kubelet path",level:"internals",steps:[S("Request logs","kubectl requests the Pod log subresource through the API.",["clients","api"],"GET Pod/log","request","Pod/log"),S("Proxy to kubelet","The API server initiates a special HTTPS connection to the kubelet.",["api","kubeletA"],"PROXY HTTPS","external","Log stream"),S("Stream container logs","The kubelet retrieves node-local logs and streams them back.",["kubeletA","runtimeA","clients"],"STREAM","data","Logs")]},
 {id:19,title:"exec / attach / port-forward",short:"Streaming subresources",level:"internals",steps:[S("Open a stream","kubectl calls an exec, attach or portforward subresource.",["clients","api"],"POST /exec","request","Pod/exec"),S("Reach the kubelet","The API server opens the special node-side path.",["api","kubeletB"],"UPGRADE / STREAM","external","Stream"),S("Bridge to container","The kubelet connects the bidirectional stream to the runtime.",["kubeletB","runtimeB","podsB","clients"],"BIDIRECTIONAL STREAM","data","stdin/stdout")]},
 {id:20,title:"Leader Election",short:"Coordination through a Lease",level:"internals",steps:[S("Compete through API state","Controller-manager replicas read and update a Lease.",["controllers","api"],"GET / UPDATE Lease","request","Lease"),S("One replica leads","A owns the Lease; B remains ready and attempts renewal.",["controllers","api"],"A = LEADER","status","Lease"),S("Fail over","When A fails and the Lease expires, B acquires leadership.",["controllers","api"],"B ACQUIRES Lease","failure","Lease")]},
 {id:21,title:"API Aggregation / Metrics",short:"One surface, extended APIs",level:"internals",steps:[S("Discover metrics API","The client discovers metrics.k8s.io through the shared API surface.",["clients","api"],"GET /apis","request","APIResourceList"),S("Route aggregated request","kube-apiserver proxies to the registered aggregated API server.",["api","external"],"GET metrics.k8s.io","external","NodeMetrics"),S("Return provider data","Metrics Server implements the resource API behind that surface.",["external","api","clients"],"RESPONSE","external","PodMetrics")]},
 {id:22,title:"API Server Failure",short:"Control impaired, Pods remain",level:"internals",steps:[S("Stop the API server","The shared state gateway becomes unavailable.",["api"],"UNAVAILABLE","failure","API"),S("Data plane continues","Already-running containers and programmed forwarding do not vanish.",["podsA","podsB","network"],"STILL RUNNING","data","Workloads"),S("Coordination stalls","kubectl, scheduling, reconciliation, status and writes are impaired.",["clients","controllers","scheduler","kubeletA","kubeletB"],"CONNECTION FAILED","failure","Requests")]},
 {id:23,title:"HA API Servers",short:"Concurrent serving, shared state",level:"internals",steps:[S("Use one endpoint","Clients reach a load-balanced control-plane endpoint.",["clients","api"],"HTTPS","request","Request"),S("Serve concurrently","Multiple API-server replicas serve requests concurrently; no one active leader.",["api","etcd"],"API1 + API2 + API3","event","API replicas"),S("Lose one replica","Health checks remove a failed replica; survivors continue.",["api","clients"],"API2 FAILED","failure","API replica"),S("Respect dependencies","Availability still depends on etcd quorum and healthy routing.",["api","etcd"],"QUORUM REQUIRED","failure","etcd quorum")]}
];

const nodes:Record<NodeId,{label:string;sub:string;x:number;y:number;w:number;h:number;group:string;icon:string;min:Level;desc:string}>={
 clients:{label:"API clients",sub:"kubectl · Helm · GitOps · SDK",x:410,y:24,w:220,h:54,group:"outside",icon:"⌘",min:"foundation",desc:"Humans and automation express intent through the Kubernetes API."},
 controllers:{label:"Controller manager",sub:"many reconciliation loops",x:86,y:178,w:204,h:64,group:"control",icon:"↻",min:"foundation",desc:"Hosts independent controllers that observe, compare and act."},
 api:{label:"kube-apiserver",sub:"state gateway · policy · API",x:400,y:146,w:240,h:92,group:"control",icon:"K",min:"foundation",desc:"Serves the API and mediates access to shared cluster state."},
 etcd:{label:"etcd",sub:"durable cluster memory",x:436,y:278,w:168,h:60,group:"control",icon:"DB",min:"foundation",desc:"Durable distributed key-value store backing API state."},
 scheduler:{label:"Scheduler",sub:"placement decisions",x:748,y:178,w:184,h:64,group:"control",icon:"◇",min:"foundation",desc:"Selects Nodes for Pods; it does not start containers."},
 external:{label:"External systems",sub:"cloud · webhook · metrics",x:790,y:22,w:192,h:58,group:"external",icon:"↗",min:"internals",desc:"Provider APIs, webhooks, aggregated APIs and operators."},
 nodeA:{label:"worker-a",sub:"ready · 4 vCPU · 16 GiB",x:58,y:426,w:410,h:268,group:"node",icon:"A",min:"foundation",desc:"A worker Node containing node agents, runtime and Pods."},
 nodeB:{label:"worker-b",sub:"ready · 8 vCPU · 32 GiB",x:570,y:426,w:410,h:268,group:"node",icon:"B",min:"foundation",desc:"A second worker Node preserving multi-node context."},
 kubeletA:{label:"kubelet",sub:"node execution agent",x:88,y:482,w:164,h:58,group:"node",icon:"κ",min:"foundation",desc:"Reconciles assigned PodSpecs into worker-a reality."},
 kubeletB:{label:"kubelet",sub:"node execution agent",x:600,y:482,w:164,h:58,group:"node",icon:"κ",min:"foundation",desc:"Observes Pods assigned to worker-b and reports reality."},
 runtimeA:{label:"containerd",sub:"CRI runtime",x:88,y:586,w:142,h:52,group:"node",icon:"□",min:"foundation",desc:"Creates and manages containers after kubelet requests."},
 runtimeB:{label:"containerd",sub:"CRI runtime",x:600,y:586,w:142,h:52,group:"node",icon:"□",min:"foundation",desc:"The node-local container execution engine."},
 podsA:{label:"Pods",sub:"web-7b9 · api-4df",x:278,y:566,w:156,h:88,group:"workload",icon:"⬡",min:"foundation",desc:"Running workloads; app traffic bypasses kube-apiserver."},
 podsB:{label:"Pods",sub:"web-2k1 · worker-8c2",x:790,y:566,w:156,h:88,group:"workload",icon:"⬡",min:"foundation",desc:"Assigned desired state made real by kubelet and runtime."},
 network:{label:"Service dataplane",sub:"kube-proxy / eBPF · CNI",x:316,y:472,w:124,h:62,group:"node",icon:"⇄",min:"practitioner",desc:"Implements Service forwarding and Pod networking."},
 storage:{label:"CSI",sub:"controller + node",x:826,y:472,w:124,h:62,group:"node",icon:"▱",min:"practitioner",desc:"Integrates provisioning, attachment and node-side mounts."}
};
const edges:{a:NodeId;b:NodeId;label:string;kind:Step["kind"]}[]=[
 {a:"clients",b:"api",label:"HTTPS API",kind:"request"},{a:"controllers",b:"api",label:"LIST · WATCH · WRITE",kind:"watch"},{a:"scheduler",b:"api",label:"WATCH · BIND",kind:"watch"},{a:"api",b:"etcd",label:"STORAGE",kind:"request"},{a:"api",b:"kubeletA",label:"API / SPECIAL",kind:"watch"},{a:"api",b:"kubeletB",label:"API / SPECIAL",kind:"watch"},{a:"kubeletA",b:"runtimeA",label:"CRI",kind:"data"},{a:"runtimeA",b:"podsA",label:"EXECUTES",kind:"data"},{a:"kubeletB",b:"runtimeB",label:"CRI",kind:"data"},{a:"runtimeB",b:"podsB",label:"EXECUTES",kind:"data"},{a:"api",b:"external",label:"WEBHOOK / AGGREGATION",kind:"external"},{a:"network",b:"podsA",label:"SERVICE TRAFFIC",kind:"data"},{a:"network",b:"podsB",label:"SERVICE TRAFFIC",kind:"data"},{a:"storage",b:"podsB",label:"MOUNT",kind:"external"}];
const levelRank:Record<Level,number>={foundation:0,practitioner:1,internals:2};
const componentDetails:Record<string,{role:string;reads:string;watches:string;writes:string;why:string;not:string}>={
 api:{role:"Central exchange / state gateway",reads:"API resources through its storage layer",watches:"Storage changes for delivery and caches",writes:"Validated API state",why:"One versioned, secured coordination surface",not:"Ordinary application data-plane packets"},
 controllers:{role:"Reconciliation / decision engines",reads:"Desired and observed objects",watches:"Deployments, Pods, Nodes, Services and more",writes:"Child objects, metadata and status",why:"Move actual state toward desired state",not:"Normally command kubelets or access etcd directly"},
 scheduler:{role:"Placement decision engine",reads:"Pods, Nodes, resources and constraints",watches:"Unscheduled Pods and scheduling inputs",writes:"Pod binding / nodeName decision",why:"Choose a feasible Node",not:"Start containers, SSH to Nodes, or command kubelets"},
 etcd:{role:"Durable cluster memory",reads:"Storage requests from kube-apiserver",watches:"Internal storage changes",writes:"Versioned key-value state",why:"Consistent durable backing",not:"Serve as the public API for ordinary clients"},
 kubeletA:{role:"Node execution agent",reads:"Assigned PodSpecs, ConfigMaps, Secrets",watches:"Pods assigned to worker-a",writes:"Pod status, Node status and Leases",why:"Turn API intent into worker-a reality",not:"Act as a cluster-wide controller"},
 kubeletB:{role:"Node execution agent",reads:"Assigned PodSpecs, ConfigMaps, Secrets",watches:"Pods assigned to worker-b",writes:"Pod status, Node status and Leases",why:"Turn API intent into worker-b reality",not:"Receive start commands from the scheduler"},
 network:{role:"Service and Pod dataplane",reads:"Services and EndpointSlices",watches:"Routing-relevant resources",writes:"Node-local forwarding state",why:"Route traffic without kube-apiserver",not:"Store desired cluster state"},
 storage:{role:"Storage integration",reads:"PVC, PV, Pod and attachment state",watches:"Claims and volume objects",writes:"PV, binding and status",why:"Bridge API objects to providers",not:"Send bulk data through kube-apiserver"}
};
const modes=[{id:"explore" as Mode,label:"Explore",icon:Search,hint:"Inspect components"},{id:"flow" as Mode,label:"Play a flow",icon:Play,hint:"Trace 23 scenarios"},{id:"gates" as Mode,label:"Request gates",icon:ShieldCheck,hint:"Follow API processing"},{id:"failure" as Mode,label:"Fail something",icon:Zap,hint:"Test resilience"},{id:"advanced" as Mode,label:"Advanced",icon:Braces,hint:"Reveal internals"}];
const gateFailures=[["Bad certificate / token","Authentication","401 Unauthorized"],["RBAC denied","Authorization","403 Forbidden"],["Namespace missing","Resource routing","404 Not Found"],["Quota exceeded","Admission","403 Forbidden"],["PodSecurity violation","Admission","403 Forbidden"],["Webhook denied","Admission","denied by webhook"],["Webhook timeout","Admission","timeout / failurePolicy"],["Malformed object","Validation","422 Unprocessable Entity"],["Stale resourceVersion","Storage","409 Conflict"],["API overload","Priority & Fairness","429 Too Many Requests"]];
const failures=[
 {name:"Kill one Pod",stops:"One container",continues:"API, other Pods, Service traffic",detects:"kubelet + ReplicaSet controller",change:"Pod status / object",reaction:"Create and schedule a replacement Pod"},
 {name:"Kill one Node",stops:"Workloads on that Node",continues:"Healthy Nodes and control plane",detects:"Missing Lease + Node status",change:"Node Ready becomes Unknown/False",reaction:"Lifecycle handling and eventual replacement"},
 {name:"Kill controller manager",stops:"Affected reconciliation loops",continues:"Running Pods, API reads/writes, scheduling",detects:"Leader election",change:"Lease stops renewing",reaction:"Standby replica acquires leadership"},
 {name:"Kill scheduler",stops:"New Pod placement",continues:"Running Pods and other reconciliation",detects:"Leader election + pending Pods",change:"Pods remain nodeName: unset",reaction:"Standby scheduler takes leadership"},
 {name:"Kill API server",stops:"Cluster state coordination",continues:"Existing workloads and dataplane",detects:"Every API client",change:"No new API state",reaction:"HA endpoint routes to healthy replicas"},
 {name:"Block webhook",stops:"Applicable admitted writes",continues:"Reads and unrelated requests",detects:"Admission timeout",change:"Object is not persisted",reaction:"failurePolicy selects fail-open or fail-closed"},
 {name:"Break etcd connectivity",stops:"Durable reads/writes",continues:"Existing data plane",detects:"kube-apiserver",change:"API operations fail or degrade",reaction:"Restore quorum/connectivity"},
 {name:"Overload API",stops:"Unprotected capacity",continues:"Higher-priority flows",detects:"API Priority and Fairness",change:"Requests queue or get 429",reaction:"Fair queuing and client backoff"}
];
function center(id:NodeId){const n=nodes[id];return{x:n.x+n.w/2,y:n.y+n.h/2}}

function Topology({active,selected,onSelect,traffic,level,failed}:{active:NodeId[];selected:string;onSelect:(id:string)=>void;traffic:Traffic;level:Level;failed?:string}){
 const visible=(id:NodeId)=>levelRank[nodes[id].min]<=levelRank[level];
 return <svg className="topology" viewBox="0 0 1040 730" role="img" aria-label="Kubernetes cluster topology centered on kube-apiserver">
  <defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7 Z" fill="currentColor"/></marker><pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="rgba(130,156,190,.08)"/></pattern></defs>
  <rect width="1040" height="730" fill="url(#grid)"/><text x="32" y="44" className="zone-label">OUTSIDE CLUSTER</text><rect x="28" y="104" width="984" height="266" rx="20" className="zone control-zone"/><text x="48" y="130" className="zone-label">CONTROL PLANE</text><line x1="28" x2="1012" y1="390" y2="390" className="boundary"/><text x="32" y="416" className="zone-label">WORKER NODES · DATA PLANE</text>
  {edges.map((e,i)=>{if(!visible(e.a)||!visible(e.b))return null;const a=center(e.a),b=center(e.b),hot=active.includes(e.a)&&active.includes(e.b),dim=(traffic==="control"&&e.kind==="data")||(traffic==="data"&&e.kind!=="data");return <g key={i} className={`edge ${e.kind} ${hot?"active":""} ${dim?"dim":""}`} onClick={()=>onSelect(`edge-${i}`)} role="button" tabIndex={0} aria-label={`${nodes[e.a].label} to ${nodes[e.b].label}: ${e.label}`}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} markerEnd="url(#arrow)"/>{hot&&<circle r="5" className="packet"><animateMotion dur="1.6s" repeatCount="indefinite" path={`M${a.x},${a.y} L${b.x},${b.y}`}/></circle>}{hot&&<g className="edge-badge"><rect x={(a.x+b.x)/2-46} y={(a.y+b.y)/2-11} width="92" height="22" rx="6"/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2+4}>{e.label}</text></g>}</g>})}
  {(Object.keys(nodes) as NodeId[]).map(id=>{if(!visible(id))return null;const n=nodes[id],hot=active.includes(id),dead=(failed==="Kill API server"&&id==="api")||(failed==="Kill one Node"&&["nodeB","kubeletB","podsB"].includes(id)),container=id==="nodeA"||id==="nodeB";return <g key={id} className={`node ${n.group} ${hot?"active":""} ${selected===id?"selected":""} ${dead?"dead":""}`} role="button" tabIndex={0} aria-label={`${n.label}: ${n.desc}`} onClick={()=>onSelect(id)} onKeyDown={e=>{if(e.key==="Enter")onSelect(id)}}><rect x={n.x} y={n.y} width={n.w} height={n.h} rx={container?18:12}/>{container?<><text x={n.x+20} y={n.y+30} className="node-title">{n.label}</text><text x={n.x+n.w-20} y={n.y+29} textAnchor="end" className="node-sub">{n.sub}</text></>:<><rect x={n.x+12} y={n.y+12} width={n.h-24} height={n.h-24} rx="9" className="node-icon-box"/><text x={n.x+12+(n.h-24)/2} y={n.y+n.h/2+5} textAnchor="middle" className="node-icon">{n.icon}</text><text x={n.x+n.h} y={n.y+n.h/2-4} className="node-title">{n.label}</text><text x={n.x+n.h} y={n.y+n.h/2+17} className="node-sub">{n.sub}</text></>}{dead&&<><line x1={n.x+8} y1={n.y+8} x2={n.x+n.w-8} y2={n.y+n.h-8} className="dead-line"/><line x1={n.x+n.w-8} y1={n.y+8} x2={n.x+8} y2={n.y+n.h-8} className="dead-line"/></>}</g>})}
  {traffic!=="control"&&<g className="data-path"><path d="M0 620 C120 720 320 690 370 610 S760 520 1040 640"/><text x="462" y="646">APPLICATION TRAFFIC · BYPASSES API SERVER</text></g>}
 </svg>
}

function GateView({failure}:{failure:number}){const gates=["TLS / ROUTING","AUTHENTICATION","AUTHORIZATION","MUTATING","VALIDATING","PROCESS + VALIDATE","PERSISTENCE","etcd"],stop=gateFailures[failure][1],stopIndex=stop==="Authentication"?1:stop==="Authorization"?2:stop==="Admission"?4:stop==="Validation"?5:stop==="Storage"?6:0;return <div className="gate-view"><div className="request-card"><span>REQUEST</span><code>alice · create · deployments · production</code></div><div className="gate-track">{gates.map((g,i)=><div key={g} className={`gate ${i<stopIndex?"passed":""} ${i===stopIndex?"stopped":""} ${i>stopIndex?"unreached":""}`}><span className="gate-num">{String(i+1).padStart(2,"0")}</span><div><b>{g}</b><small>{g==="AUTHENTICATION"?"Who are you?":g==="AUTHORIZATION"?"Can you do this?":g==="MUTATING"?"May this object be changed?":g==="VALIDATING"?"Should this object be allowed?":g==="etcd"?"Durable backing state":"Request processing"}</small></div><span className="gate-state">{i<stopIndex?"PASS":i===stopIndex?"STOP":"NOT REACHED"}</span></div>)}</div><div className="stop-result"><X size={18}/><div><b>{gateFailures[failure][2]}</b><span>Stopped at {gateFailures[failure][1]}. Everything below is untouched; etcd state is unchanged.</span></div></div></div>}

function Inspector({selected,step,onClose}:{selected:string;step:Step;onClose:()=>void}){const id=selected as NodeId,n=nodes[id],d=componentDetails[id];return <aside className="inspector"><div className="inspector-head"><div><span className="eyebrow">CONVERSATION INSPECTOR</span><h2>{n?.label||step.title}</h2></div><button className="icon-btn" onClick={onClose} aria-label="Close inspector"><X size={18}/></button></div>{n&&<p className="inspector-lede">{n.desc}</p>}{d?<div className="facts">{[["MENTAL MODEL",d.role],["READS",d.reads],["WATCHES",d.watches],["WRITES",d.writes],["WHY",d.why],["DOES NOT",d.not]].map(([k,v])=><div key={k}><span>{k}</span><p>{v}</p></div>)}</div>:<><div className={`operation ${step.kind}`}><span>{step.op||"OBSERVE"}</span><b>{step.object||"API state"}</b></div><p className="step-copy">{step.detail}</p><div className="mini-rule"><Info size={16}/><span>Components primarily coordinate by observing and changing shared API state.</span></div></>}<div className="inspector-section"><div className="section-title"><Code2 size={15}/> CURRENT OBJECT</div><pre>{step.yaml||`kind: ${step.object||"Pod"}\nmetadata:\n  resourceVersion: "18422"\nstatus:\n  observed: true`}</pre></div><div className="myth-card"><span>MYTH CHECK</span><p>{id==="scheduler"?"Scheduler starts Pods.":id==="etcd"?"Every component talks directly to etcd.":"Controllers tell kubelets what to do."}</p><b>{id==="scheduler"?"Scheduler selects Nodes; kubelets execute.":id==="etcd"?"Ordinary clients use the API server.":"They usually coordinate indirectly through API state."}</b></div></aside>}

export default function Home(){
 const[mode,setMode]=useState<Mode>("flow"),[level,setLevel]=useState<Level>("foundation"),[traffic,setTraffic]=useState<Traffic>("control"),[flowId,setFlowId]=useState(1),[stepIndex,setStepIndex]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[selected,setSelected]=useState("api"),[inspectorOpen,setInspectorOpen]=useState(true),[flowOpen,setFlowOpen]=useState(false),[gateFailure,setGateFailure]=useState(1),[failed,setFailed]=useState("Kill one Pod"),[zoom,setZoom]=useState(1);
 const flow=flows.find(f=>f.id===flowId)!,step=flow.steps[stepIndex]||flow.steps[0],active:NodeId[]=mode==="flow"?step.nodes:mode==="explore"?[selected as NodeId].filter(Boolean):mode==="failure"?(failed==="Kill API server"?["api","podsA","podsB","network"]:failed==="Kill one Node"?["nodeB","controllers","api"]:["controllers","api"]):["api"];
 const setFlow=useCallback((id:number)=>{const f=flows.find(x=>x.id===id)!;setFlowId(id);setStepIndex(0);setPlaying(false);setLevel(f.level);setMode("flow");setFlowOpen(false);setSelected("api")},[]),advance=useCallback((d:number)=>setStepIndex(i=>Math.max(0,Math.min(flow.steps.length-1,i+d))),[flow.steps.length]);
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>setStepIndex(i=>i>=flow.steps.length-1?0:i+1),2400/speed);return()=>clearInterval(t)},[playing,speed,flow.steps.length]);
 useEffect(()=>{const k=(e:KeyboardEvent)=>{if(e.key==="ArrowRight")advance(1);if(e.key==="ArrowLeft")advance(-1);if(e.key===" "){e.preventDefault();setPlaying(p=>!p)}if(e.key==="Escape"){setInspectorOpen(false);setFlowOpen(false)}};window.addEventListener("keydown",k);return()=>window.removeEventListener("keydown",k)},[advance]);
 const selectNode=(id:string)=>{setSelected(id);setInspectorOpen(true);if(mode!=="flow")setMode("explore")},filteredFlows=useMemo(()=>flows.filter(f=>levelRank[f.level]<=levelRank[level]),[level]);
 return <main className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark">K</div><div><span>KUBERNETES · CONTROL PLANE</span><h1>Every conversation goes through the API</h1></div></div><div className="top-state"><span className="live-dot"/>CLUSTER CONNECTED <code>v1.34</code></div><div className="top-actions"><div className="segmented compact">{(["foundation","practitioner","internals"] as Level[]).map(l=><button key={l} className={level===l?"active":""} onClick={()=>setLevel(l)}>{l==="foundation"?"01 Foundation":l==="practitioner"?"02 Practitioner":"03 Internals"}</button>)}</div><button className="icon-btn" aria-label="About"><CircleHelp size={18}/></button></div></header>
 <div className="workspace"><nav className="mode-rail" aria-label="Learning modes"><div className="rail-title">MODES</div>{modes.map(m=>{const I=m.icon;return <button key={m.id} className={mode===m.id?"active":""} onClick={()=>setMode(m.id)} title={m.hint}><I size={19}/><span>{m.label}</span></button>})}<div className="rail-spacer"/><div className="traffic-switch"><span>VIEW</span>{(["control","data","both"] as Traffic[]).map(t=><button key={t} className={traffic===t?"active":""} onClick={()=>setTraffic(t)}>{t}</button>)}</div></nav>
 <section className="stage"><div className="stage-toolbar"><div className="flow-picker-wrap"><button className="flow-picker" onClick={()=>setFlowOpen(o=>!o)}><span className="flow-number">{String(flow.id).padStart(2,"0")}</span><div><small>ACTIVE FLOW</small><b>{flow.title}</b></div><ChevronRight size={17} className={flowOpen?"rotate":""}/></button>{flowOpen&&<div className="flow-menu"><div className="flow-menu-head"><div><b>Play a cluster flow</b><span>Every scenario reuses this same topology</span></div><button className="icon-btn" onClick={()=>setFlowOpen(false)}><X size={16}/></button></div><div className="flow-grid">{filteredFlows.map(f=><button key={f.id} className={f.id===flow.id?"active":""} onClick={()=>setFlow(f.id)}><span>{String(f.id).padStart(2,"0")}</span><div><b>{f.title}</b><small>{f.short}</small></div></button>)}</div></div>}</div><div className="legend"><span className="solid">API request</span><span className="dashed">WATCH</span><span className="double">External</span><span className="thick">Data plane</span></div><div className="zoom-controls"><button onClick={()=>setZoom(z=>Math.max(.75,z-.1))}><ZoomOut size={16}/></button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(1.35,z+.1))}><ZoomIn size={16}/></button></div></div>
 <div className="canvas-wrap">{mode==="gates"?<div className="special-canvas"><div className="special-head"><div><span className="eyebrow">REQUEST GATES</span><h2>Follow one request through kube-apiserver</h2><p>A teaching pipeline: authentication → authorization → admission for writes → persistence.</p></div><div className="read-write"><button>READ</button><button className="active">WRITE</button></div></div><GateView failure={gateFailure}/></div>:mode==="advanced"?<div className="special-canvas advanced-canvas"><div className="special-head"><div><span className="eyebrow">INTERNALS</span><h2>Kubernetes reacts instead of constantly asking</h2><p>Reveal caches, watches and queues that make control loops scalable.</p></div></div><div className="watch-lab"><div className="watch-column"><span>API SERVER</span>{[["API handlers","auth · policy · routing"],["Watch cache","serve many watches efficiently"],["Storage interface","durable state backed by etcd"]].map(x=><div className="lab-card" key={x[0]}><b>{x[0]}</b><small>{x[1]}</small></div>)}</div><div className="watch-line"><span>LIST initial state</span><span>WATCH from resourceVersion</span><span>ADDED · MODIFIED · DELETED</span></div><div className="watch-column"><span>CONTROLLER PROCESS</span>{["Reflector","Local informer cache","Event handlers","Work queue","Reconcile()"].map((x,i)=><div className={`lab-card ${i===4?"reconcile":""}`} key={x}><b>{x}</b><small>{["Maintains LIST / WATCH","Local indexed state","Changes become work","Rate-limited keys","Observe · Compare · Act"][i]}</small></div>)}</div></div><div className="advanced-row">{[["API Priority & Fairness","Protect capacity from noisy clients"],["API aggregation","Extend the API with Metrics Server"],["Leader election","Use Leases for coordination"],["Audit trail","Observe request lifecycle stages"]].map(x=><button key={x[0]}><Braces size={16}/><b>{x[0]}</b><span>{x[1]}</span></button>)}</div></div>:<div className="canvas" style={{"--zoom":zoom} as React.CSSProperties}><Topology active={active} selected={selected} onSelect={selectNode} traffic={traffic} level={level} failed={mode==="failure"?failed:undefined}/>{mode==="flow"&&<div className={`focus-callout ${step.kind}`}><span>{step.op}</span><b>{step.title}</b><p>{step.detail}</p>{step.desired!==undefined&&<div className="state-meter"><small>DESIRED {step.desired}</small><i><em style={{width:`${(step.desired||0)/3*100}%`}}/></i><small>OBSERVED {step.observed}</small><i><em className="observed" style={{width:`${(step.observed||0)/3*100}%`}}/></i></div>}</div>}{mode==="failure"&&<div className="failure-overlay"><AlertTriangle size={17}/><div><span>FAILURE INJECTED</span><b>{failed}</b></div></div>}</div>}</div>
 {mode==="gates"&&<div className="scenario-strip"><span>STOP REQUEST AT</span>{gateFailures.map((f,i)=><button key={f[0]} className={gateFailure===i?"active":""} onClick={()=>setGateFailure(i)}>{f[0]}</button>)}</div>}{mode==="failure"&&<div className="scenario-strip"><span>FAILURE PLAYGROUND</span>{failures.map(f=><button key={f.name} className={failed===f.name?"active":""} onClick={()=>setFailed(f.name)}>{f.name}</button>)}</div>}</section>
 {inspectorOpen&&mode!=="gates"&&mode!=="advanced"&&<Inspector selected={selected} step={step} onClose={()=>setInspectorOpen(false)}/>} {mode==="gates"&&<aside className="inspector gate-inspector"><span className="eyebrow">FAILURE TRACE</span><h2>{gateFailures[gateFailure][0]}</h2><div className="trace-list">{["TLS request received","Identity established","Permission checked","Admission evaluated","Object validated","State committed"].map((x,i)=>{const stop=gateFailures[gateFailure][1],si=stop==="Authentication"?1:stop==="Authorization"?2:stop==="Admission"?3:stop==="Validation"?4:5;return <div key={x} className={i<si?"pass":i===si?"stop":"skip"}><span>{i<si?"✓":i===si?"×":"—"}</span><b>{x}</b><small>{i<si?"completed":i===si?gateFailures[gateFailure][2]:"not reached"}</small></div>})}</div><div className="mini-rule"><LockKeyhole size={16}/><span>Authentication establishes identity. Authorization decides what it may do.</span></div><div className="admission-note"><b>Read vs write</b><p>GET, LIST and WATCH bypass normal admission. Resource-changing requests do not.</p></div></aside>}{mode==="failure"&&<aside className="inspector failure-inspector"><span className="eyebrow">BLAST RADIUS</span><h2>{failed}</h2>{Object.entries(failures.find(f=>f.name===failed)!).filter(([k])=>k!=="name").map(([k,v])=><div className="impact" key={k}><span>{k.toUpperCase()}</span><p>{v}</p></div>)}<div className="myth-card"><span>CONTROL ≠ DATA PLANE</span><p>Does the running workload vanish?</p><b>{failed==="Kill API server"?"No. Existing workloads can continue while coordination is impaired.":"Only affected scope stops; independent components continue."}</b></div></aside>}</div>
 <footer className="timeline"><div className="timeline-summary"><span className="eyebrow">NOW OBSERVING</span><b>{mode==="flow"?step.title:mode==="gates"?`Stopped at ${gateFailures[gateFailure][1]}`:mode==="failure"?failed:"Shared API state"}</b></div>{mode==="flow"?<><div className="step-track">{flow.steps.map((s,i)=><button key={s.title} className={i===stepIndex?"active":i<stepIndex?"done":""} onClick={()=>setStepIndex(i)}><span>{i+1}</span><b>{s.title}</b></button>)}</div><div className="playback"><button onClick={()=>setStepIndex(0)}><SkipBack size={17}/></button><button onClick={()=>advance(-1)}><ChevronLeft size={19}/></button><button className="play" onClick={()=>setPlaying(p=>!p)}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><button onClick={()=>advance(1)}><ChevronRight size={19}/></button><button onClick={()=>setStepIndex(flow.steps.length-1)}><SkipForward size={17}/></button><select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option></select></div></>:<div className="principle"><Workflow size={17}/><span>OBSERVE</span><i/><span>COMPARE</span><i/><span>ACT</span><i/><span>UPDATE API</span><i/><span>OBSERVE AGAIN</span></div>}</footer></main>
}
