import type { LinuxPillar } from '../linux-types';
import { man, systemd, nftables } from '../linux-types';

export const networkingPillar: LinuxPillar = {
  id: 'networking',
  name: 'Networking',
  short: 'Networking',
  promise: 'Let\'s follow a network connection from a humble socket, through the maze of Linux routing, and out the eth0 door.',
  hints: 'IP · routes · sockets · DNS · firewall · namespaces',
  bridge: 'Understanding how Linux handles routing and namespaces is critical to grasping ENI mappings, Security Groups, Pod networking, and CNI plugins.',
  groups: [
    { label: 'Connection path', viewIds: ['socket', 'outbound', 'route', 'dns'] },
    { label: 'Reachability', viewIds: ['listener', 'firewall-chains', 'net-ns', 'blocked'] },
  ],
  views: [
    {
      id: 'socket',
      label: 'Service socket',
      title: 'Ports don\'t open themselves. A process must ask for one.',
      question: 'How does a process listen for connections?',
      kind: 'path',
      actors: [
        { label: 'Process', detail: 'The application (e.g., nginx)' },
        { label: 'Socket API', detail: 'Calls socket(), bind(), and listen()' },
        { label: 'TCP :443', detail: 'The kernel allocates the port and queues connections' },
        { label: 'Incoming Traffic', detail: 'Clients can now connect' },
      ],
      explanation: 'A port isn\'t a physical thing; it\'s just a number assigned to a process via a socket. If you see a port is closed, it usually means no process has successfully called bind() and listen() on that port number.',
      takeaway: 'If a port is open, a specific process is holding it open via a socket.',
      command: 'ss -tlnp | grep :443',
      output: 'LISTEN 0 511 0.0.0.0:443 0.0.0.0:* users:(("nginx",pid=1025,fd=11))',
      probe: 'lsof -i :443',
      probeOutput: 'COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME\nnginx   1025  www  11u  IPv4 123456      0t0  TCP *:443 (LISTEN)',
      caveat: 'Privileged ports (under 1024) require root or the CAP_NET_BIND_SERVICE capability.',
      source: `${man}man8/ss.8.html`,
    },
    {
      id: 'outbound',
      label: 'Outbound trace',
      title: 'A multi-step journey to the outside world.',
      question: 'What actually happens when I run curl example.com?',
      kind: 'path',
      actors: [
        { label: 'DNS Resolution', detail: 'Resolves example.com to an IP address' },
        { label: 'Socket Creation', detail: 'Opens a random ephemeral port' },
        { label: 'Routing Decision', detail: 'Finds the correct interface to send packets' },
        { label: 'Firewall (OUTPUT)', detail: 'Checks if outbound traffic is allowed' },
        { label: 'Network Interface (eth0)', detail: 'Transmits the packet onto the wire' },
      ],
      explanation: 'Outgoing connections require a series of successful steps. Failure at any point — a bad DNS server, no default route, or a restrictive egress firewall — will break the connection with different error messages.',
      takeaway: 'Trace the path: DNS → socket → route → firewall → interface.',
      command: 'curl -v https://example.com',
      output: '* Trying 93.184.215.14:443...\n* Connected to example.com (93.184.215.14) port 443',
      probe: 'ip route get 93.184.215.14',
      probeOutput: '93.184.215.14 via 10.0.0.1 dev eth0 src 10.0.0.5\n    cache',
      caveat: 'Proxies, VPNs, and complex policy routing can drastically alter this flow.',
      source: `${man}man8/ip-route.8.html`,
    },
    {
      id: 'route',
      label: 'Route & neighbour',
      title: 'Next hop vs final destination.',
      question: 'How does a packet know where to go next?',
      kind: 'layers',
      actors: [
        { label: 'Final Destination IP', detail: 'The ultimate target (e.g., 8.8.8.8)' },
        { label: 'Routing Table', detail: 'Matches destination to the next hop gateway (e.g., 10.0.0.1)' },
        { label: 'Neighbour Cache (ARP)', detail: 'Resolves gateway IP to a MAC address' },
        { label: 'Ethernet Frame', detail: 'Packet sent to the gateway\'s MAC via eth0' },
      ],
      explanation: 'Linux doesn\'t care how to reach the final destination; it only cares about the next hop. The routing table finds the gateway IP, and the neighbour (ARP) table finds that gateway\'s physical MAC address. If ARP fails, the packet can\'t leave the host.',
      takeaway: 'Routing finds the next IP. ARP finds the next MAC address. Both are required.',
      command: 'ip route',
      output: 'default via 10.0.0.1 dev eth0 proto dhcp\n10.0.0.0/24 dev eth0 proto kernel scope link src 10.0.0.5',
      probe: 'ip neigh show',
      probeOutput: '10.0.0.1 dev eth0 lladdr 00:11:22:33:44:55 REACHABLE',
      caveat: 'IPv6 uses NDP (Neighbor Discovery Protocol) instead of ARP, though the concept is the same.',
      source: `${man}man8/ip-neigh.8.html`,
    },
    {
      id: 'dns',
      label: 'DNS in practice',
      title: 'Translating human names to network addresses.',
      question: 'How does Linux resolve a domain name?',
      kind: 'walkthrough',
      steps: [
        { command: 'cat /etc/resolv.conf', output: 'nameserver 127.0.0.53\nsearch localdomain', annotation: '/etc/resolv.conf is the standard file that configures DNS resolvers. 127.0.0.53 typically means systemd-resolved is running a local stub resolver.' },
        { command: 'resolvectl status', output: 'Global\n  Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported\n  resolv.conf mode: stub\n\nLink 2 (eth0)\n  Current Scopes: DNS\n  Current DNS Server: 10.0.0.2', annotation: 'If using systemd-resolved, this command shows the actual upstream DNS servers being used per interface.' },
        { command: 'dig +short example.com', output: '93.184.215.14', annotation: 'dig is the primary tool for testing DNS resolution. +short gives just the IP. If dig works but curl fails, check /etc/nsswitch.conf or /etc/hosts.' },
        { command: 'cat /etc/hosts', output: '127.0.0.1 localhost\n10.0.0.5  devbox-01', annotation: '/etc/hosts is checked before DNS. It\'s a hardcoded local override that can cause confusing resolution issues if forgotten.' },
      ],
      explanation: 'DNS resolution in modern Linux usually goes through a local stub resolver (like systemd-resolved), which then queries upstream servers. The search domain setting allows resolving short names (like "db" instead of "db.localdomain").',
      takeaway: '/etc/resolv.conf tells the system where to ask; systemd-resolved often acts as the middleman.',
      command: 'host example.com',
      output: 'example.com has address 93.184.215.14',
      probe: 'grep hosts /etc/nsswitch.conf',
      probeOutput: 'hosts: files dns',
      caveat: 'Containers might mount a custom resolv.conf bypassing the host\'s stub resolver entirely.',
      source: `${systemd}systemd-resolved.service.html`,
    },
    {
      id: 'listener',
      label: 'Bind address',
      title: 'First line of network defense.',
      question: 'Why can I curl my app locally, but not from the network?',
      kind: 'split',
      actors: [
        { label: '127.0.0.1 (Localhost)', detail: 'Only reachable from processes on the same machine' },
        { label: '0.0.0.0 (All interfaces)', detail: 'Reachable from outside via any network interface' },
        { label: 'Specific IP (e.g., 10.0.0.5)', detail: 'Only reachable via that specific interface' },
      ],
      explanation: 'When an application starts listening on a port, it must choose an IP address to bind to. Binding to 127.0.0.1 ensures the app is isolated from the network. To serve external traffic, it must bind to 0.0.0.0 (or a specific external IP).',
      takeaway: 'A service listening on 127.0.0.1 is safe from the network. A service on 0.0.0.0 is exposed.',
      command: 'ss -tlnp',
      output: 'LISTEN 0 511 127.0.0.1:8080 0.0.0.0:* users:(("node",pid=2048,fd=18))\nLISTEN 0 511 0.0.0.0:443  0.0.0.0:* users:(("nginx",pid=1025,fd=11))',
      probe: 'curl -I http://127.0.0.1:8080',
      probeOutput: 'HTTP/1.1 200 OK',
      caveat: 'IPv6 uses ::1 for localhost and :: for all interfaces.',
      source: `${man}man2/bind.2.html`,
    },
    {
      id: 'firewall-chains',
      label: 'iptables/nftables chains',
      title: 'The kernel\'s traffic cops.',
      question: 'How does the firewall filter traffic?',
      kind: 'layers',
      actors: [
        { label: 'INPUT', detail: 'Traffic destined for local sockets (e.g., incoming to nginx)' },
        { label: 'FORWARD', detail: 'Traffic routed through this host (e.g., router/container host)' },
        { label: 'OUTPUT', detail: 'Traffic generated by local processes (e.g., outgoing curl)' },
      ],
      explanation: 'Linux firewalls organize rules into chains based on the packet\'s lifecycle. If a packet is for the host itself, it traverses the INPUT chain. If the host is just acting as a router, the packet traverses the FORWARD chain. Dropping packets early saves resources.',
      takeaway: 'INPUT is for the host. FORWARD is for routing. OUTPUT is from the host.',
      command: 'sudo iptables -L INPUT -n --line-numbers',
      output: '1    ACCEPT  all  --  0.0.0.0/0  0.0.0.0/0   state RELATED,ESTABLISHED\n2    ACCEPT  tcp  --  0.0.0.0/0  0.0.0.0/0   tcp dpt:22\n3    DROP    all  --  0.0.0.0/0  0.0.0.0/0',
      probe: 'sudo nft list ruleset',
      probeOutput: 'table inet filter {\n  chain input { type filter hook input priority 0; policy drop; }',
      caveat: 'Modern systems use nftables natively, but iptables wrappers are still very common. Containers heavily manipulate these rules.',
      source: `${nftables}Netfilter_hooks`,
    },
    {
      id: 'net-ns',
      label: 'Network namespaces',
      title: 'How containers get their own network.',
      question: 'Why doesn\'t my container see the host\'s network interfaces?',
      kind: 'comparison',
      items: [
        { label: 'Host Namespace', detail: 'Has eth0, full routing table, and firewall rules.', command: 'ip link', output: '1: lo\n2: eth0', highlight: 'neutral' },
        { label: 'Container Namespace', detail: 'Isolated network stack. Has its own lo and a virtual eth0 (veth pair) linking it to the host.', command: 'ip netns exec container_ns ip link', output: '1: lo\n5: eth0@if6', highlight: 'neutral' },
      ],
      explanation: 'Network namespaces partition the kernel\'s network stack. A process in a network namespace has its own interfaces, routing tables, and firewall rules, completely independent of the host. This is the core networking isolation primitive for Docker and Kubernetes.',
      takeaway: 'Containers live in alternate network realities. What you see on the host isn\'t what they see.',
      command: 'ip netns list',
      output: 'container_ns (id: 0)',
      probe: 'ip netns exec container_ns ip route',
      probeOutput: 'default via 172.17.0.1 dev eth0\n172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2',
      caveat: 'Namespaces can be joined together (e.g., Kubernetes Pods share a single network namespace among multiple containers).',
      source: `${man}man7/network_namespaces.7.html`,
    },
    {
      id: 'blocked',
      label: 'Blocked path diagnosis',
      title: 'Which layer said "no"?',
      question: 'Connection refused? Timeout? What do the errors actually mean?',
      kind: 'evidence',
      actors: [
        { label: 'DNS Failure', detail: 'Could not resolve host: Name or service not known' },
        { label: 'Routing Failure', detail: 'Network is unreachable or No route to host' },
        { label: 'Firewall Drop', detail: 'Connection timed out (packets disappeared into a black hole)' },
        { label: 'Connection Refused', detail: 'Server reached, but no process is listening on that port' },
      ],
      explanation: 'Network errors aren\'t random; they accurately describe exactly where the failure occurred. A timeout usually implies a firewall drop (or dead host). A "refused" implies the host is up, the firewall allowed it, but the application service is down or not listening.',
      takeaway: 'Read the error. "Refused" means the network is fine but the app is missing. "Timeout" means the network is blocked.',
      command: 'curl -v http://10.0.0.5:81',
      output: 'curl: (7) Failed to connect to 10.0.0.5 port 81: Connection refused',
      probe: 'ping -c 1 10.0.0.5',
      probeOutput: '64 bytes from 10.0.0.5: icmp_seq=1 ttl=64 time=0.123 ms',
      caveat: 'Firewalls can be configured to REJECT instead of DROP, which immediately returns "Connection refused", blurring the line with a stopped service.',
      source: `${man}man8/ping.8.html`,
    },
  ],
};
