import type { LinuxPillar } from '../linux-types';
import { man, systemd } from '../linux-types';

export const processesPillar: LinuxPillar = {
  id: 'processes',
  name: 'Processes & Services',
  short: 'Processes',
  promise: 'Let\'s watch an executable wake up and become a running process, and see who manages its lifetime.',
  hints: 'PID · signals · FDs · systemd · env · cron',
  bridge: 'Just like processes run on Linux, containers are ultimately just isolated Linux processes, which forms the foundation of Kubernetes Pod lifecycles.',
  groups: [
    { label: 'Runtime', viewIds: ['fork', 'tree', 'fds', 'signals'] },
    { label: 'Services', viewIds: ['unit', 'unit-files', 'env-vars', 'failed'] },
  ],
  views: [
    {
      id: 'fork',
      label: 'Program to PID',
      title: 'A program is a file on disk; a process is a program in execution.',
      question: 'How does an executable file become a running process?',
      kind: 'path',
      actors: [
        { label: 'Executable File', detail: 'The binary on disk (e.g., /usr/sbin/nginx)' },
        { label: 'Service Start', detail: 'systemd calls fork() and exec() to start it' },
        { label: 'Parent PID', detail: 'The master process gets a PID (e.g., 1024)' },
        { label: 'Child PIDs', detail: 'Master forks workers to handle requests (e.g., 1025, 1026)' },
      ],
      explanation: 'When you start a service, systemd creates a new process (fork) and replaces it with the executable file (exec). The master process then typically forks child worker processes. The original file is just data; the processes are active memory, execution context, and open files.',
      takeaway: 'Executables are passive data. Processes are active runtime entities with a state.',
      command: 'ps -eo pid,ppid,cmd | grep nginx',
      output: ' 1024     1 nginx: master process\n 1025  1024 nginx: worker process',
      probe: 'stat /proc/1024/exe',
      probeOutput: '  File: /proc/1024/exe -> /usr/sbin/nginx',
      caveat: 'This shows the classic daemon model. Some modern apps don\'t daemonize or fork workers, preferring a single process model.',
      source: `${man}man2/fork.2.html`,
    },
    {
      id: 'tree',
      label: 'Process tree',
      title: 'Every process has a parent, tracking all the way back to PID 1.',
      question: 'Who started this process?',
      kind: 'tree',
      actors: [
        { label: 'PID 1 (systemd)', detail: 'The parent of all processes' },
        { label: 'PID 1024 (nginx master)', detail: 'Direct child of systemd, manages workers' },
        { label: 'PID 1025 (nginx worker)', detail: 'Handles actual client connections' },
      ],
      explanation: 'The Linux process space is a strict hierarchy. PID 1 (systemd on most distros) is the root. Every other process is created by an existing process. If a parent dies, its children are "orphaned" and usually reparented to PID 1.',
      takeaway: 'Process management cascades down the tree. Killing a master process usually shuts down its workers.',
      command: 'pstree -p 1024',
      output: 'nginx(1024)─┬─nginx(1025)\n            └─nginx(1026)',
      probe: 'cat /proc/1025/status | grep PPid',
      probeOutput: 'PPid:\t1024',
      caveat: 'Zombie processes (Z state) happen when a child exits but its parent hasn\'t read its exit status yet.',
      source: `${man}man1/pstree.1.html`,
    },
    {
      id: 'fds',
      label: 'Open handles',
      title: 'Where a process meets storage and networking.',
      question: 'How does a process interact with files and network sockets?',
      kind: 'tree',
      actors: [
        { label: 'FD 0, 1, 2', detail: 'Standard Input, Output, and Error' },
        { label: 'FD 7 (File)', detail: 'Open handle to an access log (e.g., /var/log/nginx/access.log)' },
        { label: 'FD 11 (Socket)', detail: 'Listening TCP socket on port 443' },
      ],
      explanation: 'File Descriptors (FDs) are how a Linux process accesses everything outside its own memory. Whether it\'s a file on disk, a terminal, or a network connection, it\'s represented as a number (an FD) that the kernel manages for the process.',
      takeaway: 'Everything is a file descriptor to a process. Run out of FDs, and your process stops working.',
      command: 'ls -l /proc/1025/fd',
      output: 'lrwx------ 0 -> /dev/null\nlrwx------ 1 -> /dev/null\nl-wx------ 7 -> /var/log/nginx/access.log\nlrwx------ 11 -> socket:[123456]',
      probe: 'lsof -p 1025',
      probeOutput: 'COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME\nnginx   1025  www  11u  IPv4 123456      0t0  TCP *:443 (LISTEN)',
      caveat: 'FD numbers can be reused. Lsof output can be slow on busy systems; checking /proc/PID/fd is faster.',
      source: `${man}man5/proc.5.html`,
    },
    {
      id: 'signals',
      label: 'Signals & job control',
      title: 'Signals are the kernel\'s tap on the shoulder.',
      question: 'Which signal should I send, and what will it do?',
      kind: 'reference',
      headers: ['Signal', '#', 'Default', 'When to use it'],
      rows: [
        ['SIGHUP', '1', 'Terminate', 'Reload config (many daemons catch this)'],
        ['SIGINT', '2', 'Terminate', 'Ctrl+C — polite "please stop"'],
        ['SIGQUIT', '3', 'Core dump', 'Ctrl+\\ — stop and dump for debugging'],
        ['SIGKILL', '9', 'Terminate', 'Uncatchable force kill — last resort only'],
        ['SIGTERM', '15', 'Terminate', 'Graceful shutdown — the default kill signal'],
        ['SIGSTOP', '19', 'Pause', 'Freeze the process (uncatchable)'],
        ['SIGCONT', '18', 'Resume', 'Unfreeze a stopped process (fg/bg)'],
        ['SIGUSR1', '10', 'Terminate', 'App-defined (log rotation, debug toggle)'],
      ],
      tableNote: 'SIGTERM is the default for kill and systemctl stop. Always try SIGTERM before SIGKILL — killing a process that\'s mid-write can corrupt data.',
      explanation: 'Signals are the kernel\'s way of poking a process. Some (like SIGTERM) are polite requests the process can catch and handle gracefully. Others (like SIGKILL) are immediate and uncatchable. Knowing which signal to use is the difference between a clean shutdown and a corrupted database.',
      takeaway: 'SIGTERM asks nicely; SIGKILL forces. Always try asking first.',
      command: 'kill -l',
      output: ' 1) SIGHUP\t 2) SIGINT\t 3) SIGQUIT\t 4) SIGILL\n 5) SIGTRAP\t 6) SIGABRT\t 7) SIGBUS\t 8) SIGFPE\n 9) SIGKILL\t10) SIGUSR1\t11) SIGSEGV\t12) SIGUSR2\n13) SIGPIPE\t14) SIGALRM\t15) SIGTERM',
      probe: 'kill -s SIGTERM 1024',
      probeOutput: '# Sends SIGTERM to PID 1024 (nginx master)',
      caveat: 'Signal numbers can vary on non-Linux systems. The behavior column describes the default — processes can install custom handlers for most signals except SIGKILL and SIGSTOP.',
      source: `${man}man7/signal.7.html`,
    },
    {
      id: 'unit',
      label: 'Unit state',
      title: 'Installed vs Enabled vs Active.',
      question: 'What is the actual state of my service?',
      kind: 'split',
      actors: [
        { label: 'Installed', detail: 'The unit file exists on disk' },
        { label: 'Enabled', detail: 'Symlinked to start automatically on boot' },
        { label: 'Active', detail: 'The process is currently running' },
      ],
      explanation: 'A service can be running but not enabled (won\'t survive reboot), or enabled but failed (tried to start on boot but crashed). You must distinguish between the static boot configuration (enabled) and the dynamic runtime state (active).',
      takeaway: 'Enable means "start on next boot." Start means "run right now."',
      command: 'systemctl is-enabled nginx && systemctl is-active nginx',
      output: 'enabled\nactive',
      probe: 'systemctl status nginx',
      probeOutput: '   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; preset: enabled)\n   Active: active (running)',
      caveat: 'Some services are socket-activated; they might show as inactive until a connection is made to their port.',
      source: `${systemd}systemctl.html`,
    },
    {
      id: 'unit-files',
      label: 'systemd unit files',
      title: 'A .service file is just a recipe card for systemd.',
      question: 'What goes inside a systemd unit file?',
      kind: 'walkthrough',
      steps: [
        { command: 'cat /etc/systemd/system/myapp.service', output: '[Unit]\nDescription=My Application\nAfter=network.target', annotation: 'The [Unit] section sets the description and ordering. After= means "start me after networking is ready," but it doesn\'t create a hard dependency.' },
        { command: '# [Service] section', output: '[Service]\nType=simple\nUser=appuser\nExecStart=/usr/bin/myapp\nRestart=on-failure', annotation: 'This is the heart of the unit. Type=simple means systemd considers the service started as soon as ExecStart runs. User= drops privileges. Restart=on-failure automatically restarts on crashes but not on clean exits.' },
        { command: '# [Install] section', output: '[Install]\nWantedBy=multi-user.target', annotation: 'This controls what happens when you run systemctl enable. WantedBy=multi-user.target means "start this unit when the system reaches normal multi-user mode" — which is most boots.' },
        { command: 'systemctl daemon-reload', output: '# No output on success', annotation: 'After editing any unit file, you MUST run daemon-reload. systemd caches unit definitions, so without this step, your changes are invisible.' },
      ],
      explanation: 'A systemd unit file is a plain-text recipe that tells systemd how to start, stop, and supervise a process. Understanding its three sections lets you create custom services, debug startup failures, and control exactly how your app behaves under supervision.',
      takeaway: 'A unit file is a recipe with three sections: what it is, how to run it, and when to start it.',
      command: 'systemctl cat nginx',
      output: '# /lib/systemd/system/nginx.service\n[Unit]\nDescription=A high performance web server...',
      probe: 'systemctl show nginx --property=ActiveState,SubState',
      probeOutput: 'ActiveState=active\nSubState=running',
      caveat: 'Unit file paths and defaults vary by distribution. The examples use a simplified fixture; real service files often have additional hardening directives.',
      source: `${systemd}systemd.service.html`,
    },
    {
      id: 'env-vars',
      label: 'Environment variables',
      title: 'Environment variables are how context flows down the tree.',
      question: 'How does a process get its environment variables?',
      kind: 'walkthrough',
      steps: [
        { command: 'echo $PATH', output: '/usr/local/bin:/usr/bin:/bin', annotation: 'PATH tells the shell where to look for executables. The shell is just a process, and PATH is just an environment variable it reads.' },
        { command: 'cat /etc/systemd/system/myapp.service', output: 'Environment="STAGE=prod"\nEnvironmentFile=/etc/myapp/.env', annotation: 'Systemd units explicitly set variables via Environment= or load them from files via EnvironmentFile=. System services do NOT inherit your shell profile!' },
        { command: 'sudo cat /proc/1025/environ | tr "\\0" "\\n"', output: 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin\nSTAGE=prod', annotation: 'The ultimate source of truth. /proc/PID/environ shows exactly what variables a process was given when it started.' },
      ],
      explanation: 'Environment variables are an array of strings passed to a process when it starts. They are inherited from the parent process. A common trap is assuming a background service has access to the variables defined in your personal ~/.bashrc. It doesn\'t, unless explicitly provided.',
      takeaway: 'Processes inherit env vars from their parent. To see the truth, check /proc/PID/environ.',
      command: 'env | grep USER',
      output: 'USER=darshan',
      probe: 'strings /proc/$$/environ | grep PWD',
      probeOutput: 'PWD=/home/darshan',
      caveat: 'Variables might contain sensitive secrets. Be careful who can read /proc/PID/environ.',
      source: `${man}man7/environ.7.html`,
    },
    {
      id: 'failed',
      label: 'Service won\'t start',
      title: 'A decision tree for "why won\'t my service start?"',
      question: 'My service won\'t start. Where do I even begin?',
      kind: 'decision',
      decisions: [
        { id: 'start', label: 'Service won\'t start', type: 'start', next: 'q-unit' },
        { id: 'q-unit', label: 'Does the unit file exist?', type: 'question', yes: 'q-config', no: 'a-install' },
        { id: 'a-install', label: 'Install the package or create the unit file, then daemon-reload', type: 'action', next: 'q-config' },
        { id: 'q-config', label: 'Does systemctl start succeed?', type: 'question', yes: 'q-active', no: 'a-journal' },
        { id: 'a-journal', label: 'Check journalctl -u <service> -n 20 for the actual error', type: 'action', next: 'q-syntax' },
        { id: 'q-syntax', label: 'Is it a config syntax error?', type: 'question', yes: 'a-fixconfig', no: 'q-deps' },
        { id: 'a-fixconfig', label: 'Fix the config file, then systemctl restart', type: 'action', next: 'q-active' },
        { id: 'q-deps', label: 'Are required dependencies running? (DB, network, mounts)', type: 'question', yes: 'q-resources', no: 'a-deps' },
        { id: 'a-deps', label: 'Start the dependency first, or fix the unit ordering', type: 'action', next: 'q-active' },
        { id: 'q-resources', label: 'Does the process have the right permissions, ports, and disk space?', type: 'question', yes: 'r-escalate', no: 'a-resources' },
        { id: 'a-resources', label: 'Fix the specific resource constraint (port conflict, disk, permissions)', type: 'action', next: 'q-active' },
        { id: 'q-active', label: 'Is the service now active and serving traffic?', type: 'question', yes: 'r-done', no: 'r-escalate' },
        { id: 'r-done', label: 'Verify with the original failing probe. Document the cause.', type: 'result' },
        { id: 'r-escalate', label: 'Collect logs, unit status, and resource state. Escalate with evidence.', type: 'result' },
      ],
      explanation: 'When a service won\'t start, resist the urge to just keep restarting it. Follow a systematic path: check if the unit exists, try to start it, read the journal, and narrow down whether it\'s a config error, missing dependency, or resource constraint.',
      takeaway: 'Follow the chain: unit exists → start attempt → journal error → narrow the cause → fix → verify.',
      command: 'systemctl status nginx --no-pager',
      output: '● nginx.service - A high performance web server\n   Loaded: loaded\n   Active: failed (Result: exit-code)',
      probe: 'journalctl -u nginx -n 5 --no-pager',
      probeOutput: 'nginx: [emerg] invalid directive "sever" in /etc/nginx/nginx.conf:12',
      caveat: 'This covers the most common failure paths. Real-world services can also fail due to SELinux/AppArmor denials, missing shared libraries, or kernel resource limits not shown here.',
      source: `${systemd}systemctl.html`,
    },
  ],
};
