import type { LinuxPillar } from '../linux-types';
import { man, bash } from '../linux-types';

export const shellPillar: LinuxPillar = {
  id: 'shell',
  name: 'Shell & Automation',
  short: 'Shell',
  promise: 'Let\'s peek behind the curtain and see how the shell parses your commands, routes the data, and reports what happened.',
  hints: 'quoting · pipes · FDs · status · grep · awk · scripts',
  bridge: 'Shell mastery directly translates to writing robust CI runners, efficient Dockerfile RUN directives, and bulletproof user-data boot scripts.',
  groups: [
    { label: 'Command execution', viewIds: ['parse', 'pipeline', 'redirection', 'text-tools'] },
    { label: 'Scripting', viewIds: ['status', 'bash-patterns', 'here-docs', 'automation'] }
  ],
  views: [
    {
      id: 'parse',
      label: 'Parse & expand',
      title: 'The shell secretly edits your command line before running it.',
      question: 'Why doesn\'t my command run exactly as I typed it?',
      kind: 'path',
      actors: [
        { label: 'Raw Input', detail: 'echo *.txt $USER' },
        { label: 'Globbing & Expansion', detail: 'Shell replaces *.txt with file list, $USER with darshan' },
        { label: 'Quote Removal', detail: 'Strips quotes used to protect literals' },
        { label: 'Execution', detail: 'execve("echo", ["file1.txt", "file2.txt", "darshan"])' }
      ],
      explanation: 'Before a program ever sees your command, the shell intercepts it. It expands variables, expands wildcards (globs), and splits arguments. This is why `ls *.txt` works — `ls` doesn\'t know how to search for `*.txt`; the shell finds the files and hands them to `ls` as a list.',
      takeaway: 'Programs don\'t see wildcards or variables. The shell processes them first.',
      command: 'set -x; echo *.txt',
      output: '+ echo a.txt b.txt\na.txt b.txt',
      probe: 'echo "*.txt"',
      probeOutput: '*.txt\n# Quotes prevent shell expansion',
      caveat: 'Different shells (Bash, Zsh, Fish) have slightly different expansion rules and behaviors, particularly around empty glob matches.',
      source: `${bash}Shell-Expansions.html`,
    },
    {
      id: 'pipeline',
      label: 'Pipe data',
      title: 'Pipes are plumbing for data streams.',
      question: 'How do commands talk to each other?',
      kind: 'path',
      actors: [
        { label: 'Producer (ls)', detail: 'Writes list of files to stdout' },
        { label: 'Kernel Pipe', detail: 'In-memory buffer connecting the two processes' },
        { label: 'Consumer (grep)', detail: 'Reads from stdin, filters, writes to stdout' }
      ],
      explanation: 'The `|` operator connects the standard output (stdout) of the left command to the standard input (stdin) of the right command. This allows you to compose complex behaviors from simple, single-purpose tools. Crucially, standard error (stderr) bypasses the pipe and goes straight to your terminal, so you still see error messages.',
      takeaway: 'Pipes let small, focused tools work together as an assembly line.',
      command: 'cat /var/log/syslog | grep "error" | wc -l',
      output: '42',
      probe: 'ls -l /proc/$$/fd',
      probeOutput: 'lrwx------ 1 root root 64 Sep 15 12:00 0 -> /dev/pts/1\nlrwx------ 1 root root 64 Sep 15 12:00 1 -> /dev/pts/1\nlrwx------ 1 root root 64 Sep 15 12:00 2 -> /dev/pts/1',
      caveat: 'Pipes are buffered. If the producer generates data too fast, it will block until the consumer reads. If the consumer exits early, the producer gets a SIGPIPE signal.',
      source: `${bash}Pipelines.html`,
    },
    {
      id: 'redirection',
      label: 'FD routing',
      title: 'Redirecting output is just changing file descriptors.',
      question: 'How do I separate normal output from error messages?',
      kind: 'split',
      actors: [
        { label: 'Command', detail: 'curl -v http://example.com' },
        { label: 'FD 1 (stdout)', detail: '> output.html (HTML payload)' },
        { label: 'FD 2 (stderr)', detail: '2> error.log (Debug headers)' },
        { label: 'Merge', detail: '2>&1 (Send errors to stdout stream)' }
      ],
      explanation: 'Every process starts with three file descriptors: 0 (stdin), 1 (stdout), and 2 (stderr). By default, 1 and 2 point to your terminal screen. Redirection (`>`, `2>`) tells the shell to point them at files instead. Order matters! `> file 2>&1` points stdout to file, then points stderr to where stdout is currently pointing (the file).',
      takeaway: '1 is data, 2 is diagnostics. Control them independently.',
      command: 'find /etc -name "*.conf" > found.txt 2> denied.txt',
      output: '# No terminal output. Matches in found.txt, permissions errors in denied.txt',
      probe: 'cat error.log',
      probeOutput: 'find: ‘/etc/ssl/private’: Permission denied',
      caveat: '`&> file` is a Bash extension that redirects both stdout and stderr. For standard POSIX compatibility in scripts, stick to `> file 2>&1`.',
      source: `${bash}Redirections.html`,
    },
    {
      id: 'text-tools',
      label: 'Text processing toolkit',
      title: 'The classic UNIX tools for slicing and dicing text.',
      question: 'Which text processing tool should I use?',
      kind: 'reference',
      headers: ['Tool', 'Best for', 'Example'],
      rows: [
        ['grep', 'Filtering lines by pattern', 'grep -i "error" /var/log/syslog'],
        ['awk', 'Extracting columns', 'awk \'{print $2, $4}\' access.log'],
        ['sed', 'Find and replace', 'sed -i \'s/old/new/g\' config.txt'],
        ['cut', 'Extracting by delimiter', 'cut -d: -f1 /etc/passwd'],
        ['sort', 'Ordering lines', 'sort -nr (numeric, reverse)'],
        ['uniq', 'Deduplication (requires sort)', 'sort | uniq -c (count duplicates)'],
        ['wc', 'Counting lines, words, bytes', 'wc -l (line count)'],
        ['xargs', 'Passing lines as arguments', 'cat files.txt | xargs rm']
      ],
      tableNote: 'These tools are Turing-complete in some cases (awk/sed), but it\'s usually better to use them for their simplest primary purpose and pipe them together.',
      explanation: 'Linux treats most configuration and logs as plain text. Mastering these few tools allows you to parse almost any data stream without writing a Python or Go script. They operate on a line-by-line basis, making them incredibly memory efficient even on gigabyte-sized log files.',
      takeaway: 'Learn awk for columns, grep for filtering, and sed for replacing.',
      command: 'cat /etc/passwd | cut -d: -f7 | sort | uniq -c | sort -nr',
      output: '     28 /usr/sbin/nologin\n      4 /bin/bash\n      1 /bin/sync\n      1 /bin/false',
      probe: 'awk -F: \'$3 >= 1000 {print $1}\' /etc/passwd',
      probeOutput: 'darshan\nappuser',
      caveat: 'Text tools assume fields are neatly delimited. Parsing complex formats like JSON or HTML with grep/awk is brittle; use jq or specialized parsers instead.',
      source: `${man}man1/grep.1.html`,
    },
    {
      id: 'status',
      label: 'Pipeline status',
      title: 'A pipeline hides failures by default.',
      question: 'Why did my script continue when a command in the pipe failed?',
      kind: 'layers',
      actors: [
        { label: 'Failing Command', detail: 'curl http://bad-url (Exits 6)' },
        { label: 'Pipe', detail: '|' },
        { label: 'Succeeding Command', detail: 'grep "OK" (Exits 1, but pipe completes)' },
        { label: 'Overall Status', detail: '$? = 1 (exit code of the LAST command)' }
      ],
      failure: {
        label: 'Enable pipefail',
        result: 'Pipeline preserves and returns the earliest failing exit code',
        output: 'set -o pipefail; curl http://bad-url | grep OK; echo $?\n# Pipeline exits 6 (curl error reported)',
        blocked: 3,
        afterActors: [
          { label: 'Failing Command', detail: 'curl http://bad-url (Exits 6)' },
          { label: 'Pipe', detail: '|' },
          { label: 'Succeeding Command', detail: 'grep "OK"' },
          { label: 'Overall Status', detail: '$? = 6 (early error caught!)' }
        ]
      },
      explanation: 'By default, the exit status of a pipeline is the exit status of the very last command. If `curl` fails to download a file, but `tar` successfully processes the empty stream, the pipe succeeds! This causes silent failures in CI/CD scripts. `set -o pipefail` changes this so the pipeline fails if ANY command fails.',
      takeaway: 'Always use set -o pipefail in scripts to expose hidden errors.',
      command: 'false | true; echo $?',
      output: '0',
      probe: 'set -o pipefail; false | true; echo $?',
      probeOutput: '1',
      caveat: 'Some tools like `grep` legitimately exit with 1 when they don\'t find a match, which will trip `pipefail` and abort your script if not handled.',
      source: `${bash}The-Set-Builtin.html`,
    },
    {
      id: 'bash-patterns',
      label: 'Bash scripting patterns',
      title: 'Common structures for reliable shell scripts.',
      question: 'How do I write loops and conditionals in Bash?',
      kind: 'walkthrough',
      steps: [
        { command: 'if [ -f "/etc/nginx/nginx.conf" ]; then\n  echo "Exists"\nfi', output: 'Exists', annotation: 'Conditionals use the [ ] test command. -f checks if a file exists, -d for directory, -z for empty string. Spacing around the brackets is strictly required.' },
        { command: 'for file in /var/log/*.log; do\n  echo "Processing $file"\ndone', output: 'Processing /var/log/syslog.log\nProcessing /var/log/auth.log', annotation: 'The for loop naturally iterates over glob matches or lists of words. Avoid iterating over `ls` output, as it breaks on filenames with spaces.' },
        { command: 'while read -r line; do\n  echo "$line"\ndone < data.txt', output: 'Line 1\nLine 2', annotation: 'This is the safest way to read a file line by line in Bash. read -r prevents backslashes from being interpreted unexpectedly.' },
        { command: 'backup() {\n  local src=$1\n  cp "$src" "$src.bak"\n}', output: '# Function defined', annotation: 'Functions take arguments as $1, $2, etc., not named parameters. Always use the `local` keyword for variables to avoid polluting the global scope.' }
      ],
      explanation: 'Bash has a full set of programming constructs, but its syntax is heavily influenced by its interactive origins. Spaces matter immensely, variable quoting is critical to prevent accidental word splitting, and functions operate more like mini-scripts than traditional programming functions.',
      takeaway: 'Quote your variables and use standard idioms to avoid edge-case bugs.',
      command: 'case "$1" in\n  start) systemctl start app ;;\n  stop)  systemctl stop app ;;\n  *)     echo "Usage: $0 {start|stop}" ;;\nesac',
      output: 'Usage: ./script.sh {start|stop}',
      probe: 'shellcheck myscript.sh',
      probeOutput: 'In myscript.sh line 4:\nif [ $var == "yes" ]; then\n     ^-- SC2086: Double quote to prevent globbing and word splitting.',
      caveat: 'For scripts longer than 100 lines, or scripts requiring complex data structures like nested JSON, strongly consider Python or Go instead of Bash.',
      source: `${bash}Shell-Commands.html`,
    },
    {
      id: 'here-docs',
      label: 'Here documents & substitution',
      title: 'Feeding multi-line strings and command outputs.',
      question: 'How do I pass complex blocks of text to a command?',
      kind: 'comparison',
      items: [
        { label: 'Here-Doc', detail: 'Pass a multi-line block of text to stdin. Variables are expanded unless EOF is quoted.', command: 'cat <<EOF\nHello $USER\nEOF', output: 'Hello darshan', highlight: 'neutral' },
        { label: 'Here-String', detail: 'Pass a single string directly to stdin without a pipe.', command: 'grep "root" <<< "$FILE_CONTENTS"', output: 'root:x:0:0:root:/root:/bin/bash', highlight: 'neutral' },
        { label: 'Command Substitution', detail: 'Capture a command\'s output into a variable. Always use $() over backticks.', command: 'TODAY=$(date +%F)\necho $TODAY', output: '2026-09-15', highlight: 'neutral' },
        { label: 'Process Substitution', detail: 'Treat a command\'s output as a temporary file. Great for tools that expect file paths, like diff.', command: 'diff <(ls dir1) <(ls dir2)', output: '1c1\n< file_a\n---\n> file_b', highlight: 'neutral' }
      ],
      explanation: 'Bash provides several syntactic shortcuts to avoid creating temporary files. Here-docs are perfect for generating config files from templates. Command substitution grabs output to use as arguments. Process substitution creates magic file descriptors that act like files but stream from commands.',
      takeaway: 'Use $() to capture output, and <<EOF to generate multi-line config files.',
      command: 'cat <<\'EOF\' > script.sh\necho "Current user: $USER"\nEOF',
      output: '# The single quotes around \'EOF\' prevent $USER from being expanded during creation',
      probe: 'cat script.sh',
      probeOutput: 'echo "Current user: $USER"',
      caveat: 'Indentation in here-docs can be tricky. Using <<-EOF allows you to indent the here-doc with tabs (but not spaces) for better script readability.',
      source: `${bash}Redirections.html`,
    },
    {
      id: 'automation',
      label: 'Real script walkthrough',
      title: 'Anatomy of a production-grade Bash script.',
      question: 'How do I write a script that won\'t break in production?',
      kind: 'recipe',
      recipeSteps: [
        { step: 'The Shebang', command: '#!/usr/bin/env bash', output: '', note: 'Always use env bash rather than /bin/bash directly to support systems where bash is installed elsewhere (like macOS Homebrew).' },
        { step: 'Strict Mode', command: 'set -euo pipefail', output: '', note: 'e: exit on error. u: exit on undefined variable. o pipefail: exit on pipe failure. This turns Bash into a much safer language.' },
        { step: 'Logging setup', command: 'log() { echo "[$(date -Iseconds)] $*" >&2; }', output: '', note: 'Create a simple logging function that writes to stderr, keeping stdout clean if the script outputs data.' },
        { step: 'Argument checking', command: 'if [ "$#" -ne 1 ]; then\n  log "Usage: $0 <dir>"; exit 1\nfi', output: '', note: 'Validate inputs early and exit with a non-zero status (1) to indicate failure to the caller.' },
        { step: 'The Work', command: 'TARGET_DIR=$1\nfind "$TARGET_DIR" -type f -name "*.tmp" -delete', output: '', note: 'Perform the actual logic. Because of strict mode, if find fails (e.g. permission denied), the script stops immediately.' }
      ],
      explanation: 'A robust script anticipates failure. By using strict mode, defining clear logging, and checking inputs, you prevent the script from bulldozing ahead when something unexpected happens. Exiting with correct status codes allows your CI/CD pipelines to know exactly when the script succeeded or failed.',
      takeaway: 'Start every script with set -euo pipefail. It prevents catastrophic half-failures.',
      command: './cleanup.sh /var/log',
      output: '[2026-09-15T12:00:00Z] Usage: ./cleanup.sh <dir>',
      probe: 'echo $?',
      probeOutput: '1',
      caveat: 'set -e can sometimes be too aggressive, terminating on commands that legitimately return non-zero (like grep). You can bypass it locally with `command || true`.',
      source: `${bash}The-Set-Builtin.html`,
    }
  ]
};
